services:
  - type: web
    name: movie-backend
    env: node
    runtime: node
    region: oregon
    plan: free
    buildCommand: ./render-build.sh
    startCommand: npm run start:prod
    dockerCommand: null
    dockerContext: null
    dockerfilePath: null
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: FRONTEND_URL
        value: https://your-frontend-app.onrender.com
      - key: MONGODB_URI
        sync: false  # You'll need to add this manually in Render dashboard
      - key: CLOUDINARY_CLOUD_NAME
        sync: false  # You'll need to add this manually in Render dashboard
      - key: CLOUDINARY_API_KEY
        sync: false  # You'll need to add this manually in Render dashboard
      - key: CLOUDINARY_API_SECRET
        sync: false  # You'll need to add this manually in Render dashboard 